services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d backend_db"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: backend_api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/backend_db
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
